using Microsoft.EntityFrameworkCore;
using SoloForte.Application.Interfaces;
using SoloForte.Domain.Entities;
using SoloForte.Infrastructure.Data;

namespace SoloForte.Infrastructure.Repositories;

public class ProductRepository : IProductRepository
{
    private readonly AppDbContext _db;
    public ProductRepository(AppDbContext db) => _db = db;

    public async Task<IEnumerable<Product>> GetAllAsync(CancellationToken ct = default) =>
        await _db.Products.AsNoTracking().OrderBy(p => p.Id).ToListAsync(ct);

    public async Task<Product?> GetByIdAsync(int id, CancellationToken ct = default) =>
        await _db.Products.FindAsync(new object?[] { id }, ct);

    public async Task<Product> AddAsync(Product entity, CancellationToken ct = default)
    {
        _db.Products.Add(entity);
        await _db.SaveChangesAsync(ct);
        return entity;
    }

    public async Task UpdateAsync(Product entity, CancellationToken ct = default)
    {
        _db.Entry(entity).State = EntityState.Modified;
        await _db.SaveChangesAsync(ct);
    }

    public async Task DeleteAsync(Product entity, CancellationToken ct = default)
    {
        _db.Products.Remove(entity);
        await _db.SaveChangesAsync(ct);
        
        // Reorganiza os IDs para manter sequência contínua
        await ReorganizeIdsAsync(ct);
    }

    public Task<bool> ExistsAsync(int id, CancellationToken ct = default) =>
        _db.Products.AnyAsync(p => p.Id == id, ct);

    private async Task ReorganizeIdsAsync(CancellationToken ct = default)
    {
        // Busca todos os produtos ordenados por ID
        var products = await _db.Products.OrderBy(p => p.Id).ToListAsync(ct);
        
        if (!products.Any())
        {
            // Se não há produtos, apenas reseta a sequência
            await ResetIdentityAsync(ct);
            return;
        }

        // Reorganiza os IDs para sequência contínua (1,2,3,4...)
        for (int i = 0; i < products.Count; i++)
        {
            int newId = i + 1;
            if (products[i].Id != newId)
            {
                products[i].Id = newId;
                _db.Entry(products[i]).Property(x => x.Id).IsModified = true;
            }
        }

        // Desabilita temporariamente o auto-increment para permitir atualização manual dos IDs
        await DisableIdentityInsertAsync(ct);
        
        try
        {
            await _db.SaveChangesAsync(ct);
        }
        finally
        {
            await EnableIdentityInsertAsync(ct);
        }

        // Ajusta o próximo valor da sequência
        await SetNextIdentityValueAsync(products.Count + 1, ct);
    }

    private async Task DisableIdentityInsertAsync(CancellationToken ct = default)
    {
        // Para PostgreSQL
        await _db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Products\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS", ct);
        
        // Para SQL Server (descomente se estiver usando SQL Server)
        // await _db.Database.ExecuteSqlRawAsync("SET IDENTITY_INSERT Products ON", ct);
    }

    private async Task EnableIdentityInsertAsync(CancellationToken ct = default)
    {
        // Para PostgreSQL
        await _db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Products\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY", ct);
        
        // Para SQL Server (descomente se estiver usando SQL Server)
        // await _db.Database.ExecuteSqlRawAsync("SET IDENTITY_INSERT Products OFF", ct);
    }

    private async Task SetNextIdentityValueAsync(int nextValue, CancellationToken ct = default)
    {
        // Para PostgreSQL
        await _db.Database.ExecuteSqlRawAsync($"SELECT setval('\"Products_Id_seq\"', {nextValue}, false)", ct);
        
        // Para SQL Server (descomente se estiver usando SQL Server)
        // await _db.Database.ExecuteSqlRawAsync($"DBCC CHECKIDENT('Products', RESEED, {nextValue - 1})", ct);
    }

    private async Task ResetIdentityAsync(CancellationToken ct = default)
    {
        // Para PostgreSQL
        await _db.Database.ExecuteSqlRawAsync("ALTER SEQUENCE \"Products_Id_seq\" RESTART WITH 1", ct);
        
        // Para SQL Server (descomente se estiver usando SQL Server)
        // await _db.Database.ExecuteSqlRawAsync("DBCC CHECKIDENT('Products', RESEED, 0)", ct);
    }
}
